package com.codewiz.wordloop.util

object IosStringKeys {
    val byEnglish = mapOf(
        "Settings" to "settings",
        "Today" to "today",
        "Library" to "library",
        "Progress" to "progress",
        "Add" to "add",
        "Add Word" to "add_word",
        "Cancel" to "cancel",
        "Done" to "done",
        "OK" to "ok",
        "Reset" to "reset",
        "Back" to "back",
        "Delete" to "delete",
        "Close" to "close",
        "View" to "view",
        "Version" to "version",
        "Account" to "account",
        "About" to "about",
        "Data" to "data",
        "Audio" to "audio",
        "Learning" to "learning",
        "Defaults" to "defaults",
        "Notifications" to "notifications",
        "Language" to "language",
        "App Language" to "app_language",
        "Choose the language for menus, buttons, and other app text." to "choose_the_language_for_menus_buttons_and_other_app_text",
        "Sign Out" to "sign_out",
        "Delete Account" to "delete_account",
        "Review Mode" to "review_mode",
        "Standard" to "standard",
        "Intensive" to "intensive",
        "Sound Effects" to "sound_effects",
        "Review Reminders" to "review_reminders",
        "Product Updates" to "product_updates",
        "Word Languages" to "word_languages",
        "Your Native Language" to "your_native_language",
        "Not set" to "not_set",
        "Export Backup" to "export_backup",
        "Import Backup" to "import_backup",
        "Importing..." to "importing",
        "Reset All Data" to "reset_all_data",
        "Open Settings" to "open_settings",
        "Signing in..." to "signing_in",
        "Search words" to "search_words",
        "All Statuses" to "all_statuses",
        "Recently Failed" to "recently_failed",
        "All Languages" to "all_languages",
        "Archive" to "archive",
        "Unarchive" to "unarchive",
        "New" to "str_new",
        "Difficult" to "difficult",
        "Mastered" to "mastered",
        "Archived" to "archived",
        "Beginner" to "beginner",
        "Intermediate" to "intermediate",
        "Advanced" to "advanced",
        "Start Review" to "start_review",
        "Practice Quiz" to "practice_quiz",
        "I don't know" to "i_don_t_know",
        "Learn a new word" to "learn_a_new_word",
        "Type any word" to "type_any_word",
        "Create learning card" to "create_learning_card",
        "Creating your card…" to "creating_your_card",
        "Word Added" to "word_added",
        "Meaning" to "meaning",
        "Examples" to "examples",
        "Synonyms" to "synonyms",
        "Antonyms" to "antonyms",
        "Get started" to "get_started",
        "Create account" to "create_account",
        "Forgot password?" to "forgot_password",
        "Sign in instead" to "sign_in_instead",
        "Check your email" to "check_your_email",
        "Review Complete" to "review_complete",
        "Practice Complete" to "practice_complete",
        "Data Transfer" to "data_transfer",
        "Backup exported." to "backup_exported",
        "Synced across devices" to "synced_across_devices",
        "Customize WordLoop for how you learn" to "customize_wordloop_for_how_you_learn",
        "Signed In As" to "signed_in_as",
        "No words yet" to "no_words_yet",
        "Add your first word to start learning." to "add_your_first_word_to_start_learning",
        "No matches" to "no_matches",
        "Words" to "words",
        "score" to "score",
        "Good morning" to "good_morning",
        "Good afternoon" to "good_afternoon",
        "Good evening" to "good_evening",
        "Good night" to "good_night",
        "Ready to review" to "ready_to_review",
        "A quick session keeps vocabulary fresh." to "a_quick_session_keeps_vocabulary_fresh",
        "All caught up!" to "all_caught_up",
        "Total XP" to "total_xp",
        "%lld word(s) waiting" to "d_word_s_waiting",
        "%lld-day streak — keep it going!" to "d_day_streak_keep_it_going",
        "Due" to "due",
        "Streak" to "streak",
        "Up next" to "up_next",
        "No reviews due right now. Add a word or check back later." to "no_reviews_due_right_now_add_a_word_or_check_back_later",
        "Your %lld-day streak is safe. Come back when new reviews are due." to "your_d_day_streak_is_safe_come_back_when_new_reviews_are_due",
    )
}
